import { Inter } from 'next/font/google'
import Main from './main'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Furnituro',
  description: 'Generated by Abajit',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Main>
          {children}
        </Main>
      </body>
    </html>
  )
}
