import '@fontsource-variable/inter';
import Main from './main'
import './globals.css'

export const metadata = {
  title: 'Furnituro',
  description: 'Generated by Abajit',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Main>
          {children}
        </Main>
      </body>
    </html>
  )
}
